### ISSUE TITLE
Use spotify API to allow user to use OAuth Authentication

### ISSUE THREAD

**Issue by AndrewCrews** [F4MAGS/Music-Buddy#7]

**Comment by AndrewCrews** [comment]
- [ ] find spotfiy Developer Site, request for API
- [ ] Implement the API's OAuth

**Comment by massimochen22** [comment]
Refactored the login since it couldn't fully get the endpoints needed. Used the spotify sdk method to fix this. For reference see issue #59

**Comment by massimochen22** [comment]
link: https://github.com/F4MAGS/Music-Buddy/commit/e113845ed04abbf25cef6338b64725693a32d52a
